Restaurant/Models/MasterMenu.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Restaurant.Models
{
    public partial class MasterMenu : BaseEntity
    {
        public int MasterMenuId { get; set; }
        public string MasterMenuName { get; set; }
        public string MasterMenuUrl { get; set; }
    }
}

Restaurant/Areas/Admin/Controllers/MasterMenuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Restaurant.Models;
using Restaurant.Models.Repositories;
using System;

namespace Restaurant.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class MasterMenuController : Controller
    {
        public IRepository<MasterMenu> MasterMenu { get; }
        public UserManager<IdentityUser> UserManager { get; }

        public MasterMenuController(IRepository<MasterMenu> _MasterMenu, UserManager<IdentityUser> _UserManager)
        {
            MasterMenu = _MasterMenu;
            UserManager = _UserManager;
        }
        // GET: MasterMenuController
        public ActionResult Index(int DeleteId)
        {
            if (DeleteId > 0)
            {
                var data2 = MasterMenu.Find(DeleteId);
                data2.EditDate = DateTime.Now;
                data2.EditUser = User.Identity.Name;
                MasterMenu.Delete(DeleteId, data2);
                return RedirectToAction(nameof(Index));
            }
            var data = MasterMenu.View();
            return View(data);
        }       

        // GET: MasterMenuController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MasterMenuController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MasterMenu collection)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError("", "SERVER CHECKING (PLEASE FILL OUT REQUIRED DATA)");
                    return View(collection);
                }
                collection.CreateDate = DateTime.Now;
                collection.CreateUser = User.Identity.Name;
                MasterMenu.Add(collection);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MasterMenuController/Edit/5
        public ActionResult Edit(int id)
        {
            var data = MasterMenu.Find(id);
            return View(data);
        }

        // POST: MasterMenuController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MasterMenu collection)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError("", "SERVER CHECKING (PLEASE FILL OUT REQUIRED DATA)");
                    return View(collection);
                }
                collection.EditDate = DateTime.Now;
                collection.EditUser = User.Identity.Name;
                MasterMenu.Update(id, collection);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ToggleActive(int id)
        {
            var data = MasterMenu.Find(id);
            data.EditDate = DateTime.Now;
            data.EditUser = User.Identity.Name;
            MasterMenu.Active(id, data);
            return RedirectToAction(nameof(Index));
        }
    }
}

Restaurant/Areas/Admin/Views/MasterMenu/Create.cshtml
@model Restaurant.Models.MasterMenu

@{
    ViewData["Title"] = "Create";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Admin/Home">Home</a></li>
            <li class="breadcrumb-item"><a href="/Admin/MasterMenu">MasterMenu</a></li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
    </nav>
</div>
<hr />
<div class="row">
    <div class="col-lg-6">

        <div class="card">
            <div class="card-body">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MasterMenuName" class="control-label"></label>
                <input asp-for="MasterMenuName" class="form-control" />
                <span asp-validation-for="MasterMenuName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MasterMenuUrl" class="control-label"></label>
                <input asp-for="MasterMenuUrl" class="form-control" />
                <span asp-validation-for="MasterMenuUrl" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>

            </div>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Restaurant/Areas/Admin/Views/MasterMenu/Edit.cshtml
@model Restaurant.Models.MasterMenu

@{
    ViewData["Title"] = "Edit";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Admin/Home">Home</a></li>
            <li class="breadcrumb-item"><a href="/Admin/MasterMenu">MasterMenu</a></li>
            <li class="breadcrumb-item active">Edit</li>
        </ol>
    </nav>
</div>
<hr />
<div class="row">
    <div class="col-lg-6">

        <div class="card">
            <div class="card-body">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MasterMenuId" />
            <div class="form-group">
                <label asp-for="MasterMenuName" class="control-label"></label>
                <input asp-for="MasterMenuName" class="form-control" />
                <span asp-validation-for="MasterMenuName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MasterMenuUrl" class="control-label"></label>
                <input asp-for="MasterMenuUrl" class="form-control" />
                <span asp-validation-for="MasterMenuUrl" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group" hidden>
                <label asp-for="CreateUser" class="control-label"></label>
                <input asp-for="CreateUser" class="form-control" />
                <span asp-validation-for="CreateUser" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
            </div></div></div></div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Restaurant/Areas/Admin/Views/MasterMenu/Index.cshtml
@model IEnumerable<Restaurant.Models.MasterMenu>

@{
    ViewData["Title"] = "Index";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Admin/Home">Home</a></li>
            <li class="breadcrumb-item"><a href="/Admin/MasterMenu">MasterMenu</a></li>
            <li class="breadcrumb-item active">Index</li>
        </ol>
    </nav>
</div>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="cardbody">
                <table id="DeleteFix" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MasterMenuName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MasterMenuUrl)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MasterMenuName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MasterMenuUrl)
            </td>
            <td>
                                    <a asp-action="Edit" asp-route-id="@item.MasterMenuId"><i class="fa-solid fa-pencil" style="font-size:20px;color:saddlebrown"></i></a> |
                    <a asp-action="ToggleActive" asp-route-id="@item.MasterMenuId">
                        @if (item.IsActive == true)
                        {
                                            <i class="fa-solid fa-eye" style="font-size:20px;"></i>
                        }
                        else
                        {
                                            <i class="fa-sharp fa-solid fa-eye-slash" style="color:red;font-size:20px;"></i>
                        }
                    </a> |
                                    <a class="btnDelete" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal"
                                       data-path="@Url.ActionLink("Index","MasterMenu",new{DeleteId=item.MasterMenuId})"> <i class="fa-regular fa-circle-xmark" style="font-size:20px;color:red"></i> </a>
            </td>
        </tr>
}
    </tbody>
</table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm Deletion</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <input type="button" class="btn btn-primary" id="btnConfirmDelete" value="Delete" />
            </div>
        </div>
    </div>
</div>
<script src="~/assets/js/vendor/jquery-v1.12.4.min.js"></script>
<script>






    var urlPathDelete = "";
    $(function () {
        //$(".btnDelete").click(function () {
        //    //alert($(this).data("path"))
        //    urlPathDelete = $(this).data("path");
        //    console.log(urlPathDelete)
        //})
        $("#DeleteFix tbody").on("click", ".btnDelete", function () {
            urlPathDelete = $(this).data("path");
            //console.log(urlPathDelete);
        });


        $("#btnConfirmDelete").click(function () {

            window.location = urlPathDelete;
        })

    });


</script>