Restaurant/Areas/Admin/Controllers/MasterCustomerReviewController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Restaurant.Models;
using Restaurant.Models.Repositories;
using Restaurant.ViewModels;
using System.IO;
using System;
using Microsoft.VisualBasic;
using Microsoft.EntityFrameworkCore.Internal;

namespace Restaurant.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MasterCustomerReviewController : Controller
    {
        public IRepository<MasterCustomerReview> MasterCustomerReview { get; }
        public IHostingEnvironment Host { get; }

        public MasterCustomerReviewController(IRepository<MasterCustomerReview> _MasterCustomerReview,IHostingEnvironment _Host)
        {
            MasterCustomerReview = _MasterCustomerReview;
            Host = _Host;
        }
        // GET: MasterCustomerReviewController
        public ActionResult Index(int DeleteId)
        {
            if (DeleteId > 0)
            {
                var data2 = MasterCustomerReview.Find(DeleteId);
                data2.EditDate = DateTime.Now;
                data2.EditUser = User.Identity.Name;
                MasterCustomerReview.Delete(DeleteId, data2);
                return RedirectToAction(nameof(Index));
            }
            var data = MasterCustomerReview.View();
            return View(data);
        }

        // GET: MasterCustomerReviewController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MasterCustomerReviewController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MasterCustomerReviewModel collection)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError("", "SERVER CHECKING (PLEASE FILL OUT REQUIRED DATA)");
                    return View(collection);
                }
                string ImageName = "";
                if (collection.File != null)
                {
                    ImageName = SaveImageName(collection.File);
                }
                var data = new MasterCustomerReview();
                data.MasterCustomerReviewId = collection.MasterCustomerReviewId;
                data.MasterCustomerReviewName = collection.MasterCustomerReviewName;
                data.MasterCustomerReviewMessage = collection.MasterCustomerReviewMessage;
                data.MasterCustomerReviewImageUrl = ImageName;
                data.IsActive = collection.IsActive;
                data.CreateDate = DateAndTime.Now;
                data.CreateUser = User.Identity.Name;
                MasterCustomerReview.Add(data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MasterCustomerReviewController/Edit/5
        public ActionResult Edit(int id)
        {
            var model = MasterCustomerReview.Find(id);
            MasterCustomerReviewModel data = new MasterCustomerReviewModel();
            data.MasterCustomerReviewName = model.MasterCustomerReviewName;
            data.MasterCustomerReviewMessage = model.MasterCustomerReviewMessage;
            data.IsActive = model.IsActive;
            data.MasterCustomerReviewId = model.MasterCustomerReviewId;
            data.MasterCustomerReviewImageUrl = model.MasterCustomerReviewImageUrl;
            data.CreateUser = model.CreateUser;
            data.CreateDate = model.CreateDate;
            return View(data);
        }

        // POST: MasterCustomerReviewController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MasterCustomerReviewModel collection)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError("", "SERVER CHECKING (PLEASE FILL OUT REQUIRED DATA)");
                    return View(collection);
                }
                string ImageName = "";
                if (collection.File != null)
                {
                    ImageName = SaveImageName(collection.File);
                }
                else
                {
                    ImageName = collection.MasterCustomerReviewImageUrl;
                }
                var data = new MasterCustomerReview();
                data.MasterCustomerReviewName = collection.MasterCustomerReviewName;
                data.MasterCustomerReviewMessage = collection.MasterCustomerReviewMessage;
                data.IsActive = collection.IsActive;
                data.MasterCustomerReviewId = collection.MasterCustomerReviewId;
                data.MasterCustomerReviewImageUrl = ImageName;
                data.CreateUser = collection.CreateUser;
                data.CreateDate = collection.CreateDate;
                data.EditDate = DateAndTime.Now;
                data.EditUser = User.Identity.Name;
                MasterCustomerReview.Update(id, data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ToggleActive(int id)
        {
            var data = MasterCustomerReview.Find(id);
            data.EditDate = DateTime.Now;
            data.EditUser = User.Identity.Name;
            MasterCustomerReview.Active(id, data);
            return RedirectToAction(nameof(Index));
        }
        public string SaveImageName(IFormFile file__)
        {
            string ImageName = "";
            if (file__ != null)
            {
                string FilePath = Path.Combine(Host.WebRootPath, "Images/MasterCustomerReviewImages");
                FileInfo file = new FileInfo(file__.FileName);
                ImageName = "Image_" + Guid.NewGuid() + file.Extension;
                string FullPath = Path.Combine(FilePath, ImageName);
                file__.CopyTo(new FileStream(FullPath, FileMode.Create));

            }
            return ImageName;
        }
    }
}

Restaurant/Areas/Admin/Views/MasterCustomerReview/Create.cshtml
@model Restaurant.ViewModels.MasterCustomerReviewModel

@{
    ViewData["Title"] = "Create";
}

<hr />
<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Admin/Home">Home</a></li>
            <li class="breadcrumb-item"><a href="/Admin/MasterCustomerReview">MasterCustomerReview</a></li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
    </nav>
</div>
<hr />
<div class="row">
    <div class="col-lg-6">

        <div class="card">
            <div class="card-body">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MasterCustomerReviewName" class="control-label"></label>
                <input asp-for="MasterCustomerReviewName" class="form-control" />
                <span asp-validation-for="MasterCustomerReviewName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MasterCustomerReviewMessage" class="control-label"></label>
                <input asp-for="MasterCustomerReviewMessage" class="form-control" />
                <span asp-validation-for="MasterCustomerReviewMessage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input asp-for="File" class="form-control" />
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div></div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Restaurant/Areas/Admin/Views/MasterCustomerReview/Edit.cshtml
@model Restaurant.ViewModels.MasterCustomerReviewModel

@{
    ViewData["Title"] = "Edit";
}

<hr />
<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Admin/Home">Home</a></li>
            <li class="breadcrumb-item"><a href="/Admin/MasterCustomerReview">MasterCustomerReview</a></li>
            <li class="breadcrumb-item active">Edit</li>
        </ol>
    </nav>
</div>
<hr />
<div class="row">
    <div class="col-lg-6">

        <div class="card">
            <div class="card-body">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MasterCustomerReviewId" />
            <div class="form-group">
                <label asp-for="MasterCustomerReviewName" class="control-label"></label>
                <input asp-for="MasterCustomerReviewName" class="form-control" />
                <span asp-validation-for="MasterCustomerReviewName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MasterCustomerReviewMessage" class="control-label"></label>
                <input asp-for="MasterCustomerReviewMessage" class="form-control" />
                <span asp-validation-for="MasterCustomerReviewMessage" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="MasterCustomerReviewImageUrl" class="control-label"></label>
                <input asp-for="MasterCustomerReviewImageUrl" class="form-control" />
                <span asp-validation-for="MasterCustomerReviewImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input asp-for="File" class="form-control" />
                <span asp-validation-for="File" class="text-danger"></span>
                <img src="~/images/MasterCustomerReviewImages/@Model.MasterCustomerReviewImageUrl" style="max-width:100px" />
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group form-check" hidden>
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDelete" /> @Html.DisplayNameFor(model => model.IsDelete)
                </label>
            </div>
            <div class="form-group" hidden>
                <label asp-for="CreateUser" class="control-label"></label>
                <input asp-for="CreateUser" class="form-control" />
                <span asp-validation-for="CreateUser" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div></div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Restaurant/Areas/Admin/Views/MasterCustomerReview/Index.cshtml
@model IEnumerable<Restaurant.Models.MasterCustomerReview>

@{
    ViewData["Title"] = "Index";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Admin/Home">Home</a></li>
            <li class="breadcrumb-item"><a href="/Admin/MasterCustomerReview">MasterCustomerReview</a></li>
            <li class="breadcrumb-item active">Index</li>
        </ol>
    </nav>
</div>
<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="cardbody">
                <table id="DeleteFix" class="table datatable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MasterCustomerReviewName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MasterCustomerReviewMessage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MasterCustomerReviewImageUrl)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MasterCustomerReviewName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MasterCustomerReviewMessage)
            </td>
            <td>
                <img src="~/images/MasterCustomerReviewImages/@item.MasterCustomerReviewImageUrl" style="max-width:100px"/>
            </td>
            <td>
                                    <a asp-action="Edit" asp-route-id="@item.MasterCustomerReviewId"><i class="fa-solid fa-pencil" style="font-size:20px;color:saddlebrown"></i></a> |
                                    <a asp-action="ToggleActive" asp-route-id="@item.MasterCustomerReviewId">
                                        @if (item.IsActive == true)
                                        {
                                            <i class="fa-solid fa-eye" style="font-size:20px;"></i>
                                        }
                                        else
                                        {
                                            <i class="fa-sharp fa-solid fa-eye-slash" style="color:red;font-size:20px;"></i>
                                        }
                                    </a> |
                                    <a class="btnDelete" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal"
                                       data-path="@Url.ActionLink("Index","MasterCustomerReview",new{DeleteId=item.MasterCustomerReviewId})"> <i class="fa-regular fa-circle-xmark" style="font-size:20px;color:red"></i> </a>
            </td>
        </tr>
}
    </tbody>
</table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm Deletion</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <input type="button" class="btn btn-primary" id="btnConfirmDelete" value="Delete" />
            </div>
        </div>
    </div>
</div>
<script src="~/assets/js/vendor/jquery-v1.12.4.min.js"></script>
<script>






    var urlPathDelete = "";
    $(function () {
        //$(".btnDelete").click(function () {
        //    //alert($(this).data("path"))
        //    urlPathDelete = $(this).data("path");
        //    console.log(urlPathDelete)
        //})
        $("#DeleteFix tbody").on("click", ".btnDelete", function () {
            urlPathDelete = $(this).data("path");
            //console.log(urlPathDelete);
        });


        $("#btnConfirmDelete").click(function () {

            window.location = urlPathDelete;
        })

    });


</script>